In [3]:
import numpy as np

In [7]:
array = np.arange(0 , 6)
print(array)

[0 1 2 3 4 5]


In [8]:
#Like other arrays you can change a specific value
array[0] = 17
print(array)

[17  1  2  3  4  5]


In [11]:
#We can also add things onto the back of arrays
array = np.arange(0 , 6)
print(np.append(array, 18))
# IMPORTANT NOTE #
#.append does not alter the original array unless we reasign it
# eg: 
array = np.append(array, 18)
print(array)

[ 0  1  2  3  4  5 18]
[ 0  1  2  3  4  5 18]


In [12]:
array = np.arange(0 , 6)
#Likewise .insert does not change the original array.
#.insert inserts at the position. 
# So the item in position lets say 3 will now be injected with the insert
# and everything else will be shifted over. No deletions
print(np.insert(array, 3 , [61, 32]))

[ 0  1  2 61 32  3  4  5]


In [14]:
#.delete removes the value at an index and shifts everything so there are only that many elements
print(np.delete(array, 4))
#also works with lists etc
Animals = ['Lions', 'Tigers' , 'Bears' , 'Wolves']
print(np.delete(Animals, 2))

[0 1 2 3 5]
['Lions' 'Tigers' 'Wolves']


In [19]:
#Numpy can perform math on all elements in an array eg:
print(array * 2)
print(array + 2 - 4)
print(array  * 2 - 2)
#however unlike mathematics code does not follow the order of operations
# It will read it as instructions eg: subtract 2 firs then multiply
print( array -2 * 2)

[ 0  2  4  6  8 10]
[-2 -1  0  1  2  3]
[-2  0  2  4  6  8]
[-4 -3 -2 -1  0  1]


In [20]:
#np .sort arranges things in ascending order by default
unsorted_array = np.array([25, 61 , 32, 54, 19 ])
print(np.sort(unsorted_array))

[19 25 32 54 61]


In [22]:
#you can make it sort in descending order
#so here I added a -1 which makes the whole array negative as demonstrated earlier
print(np.sort(-unsorted_array))
#we can fix the values by multiplying again by negative 1!
print(-np.sort(-unsorted_array))

[-61 -54 -32 -25 -19]
[61 54 32 25 19]
