In [2]:
import numpy as np

In [3]:
array_1 = np.arange(0,11)
print(array_1)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [4]:
#Like other array systems you use square brackets 0 based position. var[index]
first_element = array_1[0]
print(first_element)
last_element = array_1[10]
print(last_element)

0
10


In [5]:
#I'm a fan of python's range operator the colon :
#what a great way to say from here to there ex:  2 to 7 ==  2:7  upper bound is <7
#Remember this is 0 based index so 2 is the 3rd term.
array_range = array_1[2:7]
print(array_range)

[2 3 4 5 6]


In [6]:
#Starting position & a skip!
#Start on 4 count by 4
array_skip = array_1[4::4]
print(array_skip)

[4 8]


In [7]:
#Stat skip & go backwards o.O!!
#No surprise neagative makes it count backwards!
array_backwards = array_1[10::-3]
print(array_backwards)

[10  7  4  1]


In [8]:
array_backwards_by1 = array_1[10::-1]
print(array_backwards_by1)

[10  9  8  7  6  5  4  3  2  1  0]


In [9]:
#Best thing EVER you can count from the right hand side of the array with negative numbers.
# This will print 3 from the RH side to the end.
array_right_hand = array_1[-3:]
print(array_right_hand)

#can make it count so many from the end up to a specified point too. Beautiful!
array_right_hand_2 = array_1[-4:-2]
print(array_right_hand_2)

[ 8  9 10]
[7 8]


In [10]:
#Array length uses property .size   ...which is actually the length not the byte size
#yes 0-10 is 11 numbers/entries
print(array_1.size)

11


In [11]:
#We can find max, mins and averages of arrays!
#It doesn't like strings + var ...it likes the comma for that
print("I am the minimum! " , np.amin(array_1)) 
print("I am the maximum! " , np.amax(array_1))
print("I am the average! " , np.average(array_1))
print("I am the sum! ", np.sum(array_1))
print("I am the sum of a range of numbers! " , np.sum(array_1[6:9]))
print("I am the median! " , np.median(array_1))

I am the minimum!  0
I am the maximum!  10
I am the average!  5.0
I am the sum!  55
I am the sum of a range of numbers!  21
I am the median!  5.0
