In [58]:
import numpy as np

In [59]:
two_by_two = np.matrix([[1,2],[3,4]])
print(two_by_two)

[[1 2]
 [3 4]]


In [60]:
two_by_three = np.matrix('1 2; 3 4; 5 6')
print(two_by_three)

[[1 2]
 [3 4]
 [5 6]]


In [61]:
#This works with .ones as well 
print(np.zeros([3, 2]))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [73]:
#It's one [] for an index instead of 2 [][]
three_by_three = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(three_by_three)
print("Row:\n", three_by_three[0])
print("Column:\n", three_by_three[: , 1])
print("Multiple Columns:\n", three_by_three[:,[1,2]])
print("Index:\n", three_by_three[1, 2])
#Remember lower bound is inclusive and upper bound is exclusive
print("Multiple indicies in a row:\n", three_by_three[2, 0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Row:
 [[1 2 3]]
Column:
 [[2]
 [5]
 [8]]
Multiple Columns:
 [[2 3]
 [5 6]
 [8 9]]
Index:
 6
Multiple indicies in a row:
 [[7 8]]


In [72]:
# .size gives number of indicies
print(three_by_three.size)
# .shape gives you ( height, width ) of matrix
print("Three by Three:", three_by_three.shape)
print("Two by Three:", two_by_three.shape)

9
Three by Three: (3, 3)
Two by Three: (3, 2)


In [64]:
#matricies can be put into .amax, .amin etc 
# but also have properties you can directly call!
print(three_by_three.max())
print(three_by_three.min())

9
1


In [65]:
#Can replace indicies and rows
two_by_two[1,1] = 10
print (two_by_two)
two_by_two[1,1] = 4
two_by_two[0] = [62, 32]
print(two_by_two)
two_by_two[0] = [1, 2]


[[ 1  2]
 [ 3 10]]
[[62 32]
 [ 3  4]]


In [66]:
#You can replace columns as well
two_by_three[:, 1] = [[61], [32], [18]]
print(two_by_three)
two_by_three[:, 1] = [[2], [4], [6]]

[[ 1 61]
 [ 3 32]
 [ 5 18]]


In [67]:
#np.sort() will sort individual rows as opposed to reorganizing the whole matrix
#because this is in ascending order we're gonna print it in descending order
print(-np.sort(-three_by_three))

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [70]:
#Transpose swaps columns and rows. Or maybe more appropriately turns columns into rows
print(two_by_three)
print('Transpose:\n', two_by_three.T)
#Which means we could print a range of indicies from a column! 
# It just wont look like a column
print('Multiple Indicies in a Column:\n', two_by_three.T[1, 1:] )

[[1 2]
 [3 4]
 [5 6]]
Transpose:
 [[1 3 5]
 [2 4 6]]
Multiple Indicies in a Column:
 [[4 6]]


In [74]:
#.flatten takes a matrix and turns it into a one dimensional array
#technically just a one row'd matrix
print(three_by_three.flatten())

[[1 2 3 4 5 6 7 8 9]]


In [77]:
#matmul is matrix multiplication
print(np.matmul(two_by_two, two_by_two))

[[ 7 10]
 [15 22]]


In [78]:
image_matrix = np.matrix([[0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0]])
print(image_matrix)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [81]:
#Because we can
rows = image_matrix.shape[0]
#Remember .shape returns (height , width)
columns = image_matrix.shape[1]
print('Rows:', rows , "Columns:", columns)

#Some proof. There are two columns and 3 rows
print('Columns:', two_by_three.shape[1])


Rows: 5 Columns: 5
Columns: 2


In [82]:
#This is just a for loop. Normally we would say row in rows or animal in animals.
#I'm attempting to make it clear these are variables we name
#I am not a fan of the no brackets
for x in range(rows) :
    for y in range(columns):
        if image_matrix[x,y] == 0:
            image_matrix[x,y] = 1
        else:
            image_matrix[x,y] = 0

print(image_matrix)

[[1 1 0 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]]
