Test Holder

In [11]:
#This is a regular python array
#python arrays can be a storage for many data types
#numpy arrays are built on C and should only use numbers (Computing power!)
list_1 = [1,2,3]
print(list_1)

[1, 2, 3]


In [12]:
#Importing NumPy as whatever we want to call it really. The standard is np.
import numpy as np

In [13]:
#Creates a Numpy array based on the above array
numpy_1 = np.array(list_1)
print(numpy_1)

[1 2 3]


In [14]:
# Will create an array of x many zeroes. In this case 5 zeroes. 
zeroes_array = np.zeros(5)
print(zeroes_array)

[0. 0. 0. 0. 0.]


In [15]:
#Same as zeroes, but in this case ones.
ones_array = np.ones(5)
print(ones_array)

[1. 1. 1. 1. 1.]


In [16]:
#This makes an array of 5 numbers 0-4. The number is the upper bound ie <5
range_array_1 = np.arange(5)
print(range_array_1)

[0 1 2 3 4]


In [17]:
#This makes an array of numbers 5 to 10. Again 11 is the upper, noninclusive bound. <11
range_array_2 = np.arange(5,11)
print(range_array_2)

[ 5  6  7  8  9 10]


In [18]:
#Makes an array of numbers 0 to <20 (19). The 2 indicates every 2nd number.
range_array_3 = np.arange(0,20,2)
print(range_array_3)

[ 0  2  4  6  8 10 12 14 16 18]


In [19]:
#Same as above except the 4 indicates every 4th number.
range_array_4 = np.arange(0,20,4)
print(range_array_4)

[ 0  4  8 12 16]


In [23]:
#linspace == linear space. 
# Composed of a lower bound, upperbound and number of elements to create evenly spaced between the two.
#UNLIKE the arange function...linspace bounds ARE inclusive.
linspace_array = np.linspace(0,10,15) 
print(linspace_array)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]
